services:
  redis:
    image: redis:7.4-alpine
    container_name: drinkgenie_redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16.6
    container_name: drinkgenie_db
    environment:
      POSTGRES_DB: drinkgenie
      POSTGRES_USER: drinkgenie
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - drinkgenie_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drinkgenie -d drinkgenie"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  drinkgenie_data:
